In [2]:
import numpy as np 
import pandas as pd 
from sklearn import linear_model 
import matplotlib.pyplot as plt

In [3]:
df=pd.read_excel("/content/homeprices.xlsx")

In [4]:
df

area   price
0  2000  500000
1  2600  550000
2  3000  565000
3  3200  610000
4  3600  680000
5  4000  725000

In [9]:
area=df.area
area=area.values.reshape(-1,1)

In [8]:
price=df.price
price=price.values.reshape(-1,1)

In [10]:
model=linear_model.LinearRegression()
model.fit(area,price)

LinearRegression()

In [12]:
model.predict([[3300]])

array([[631986.84210526]])

In [23]:
df=pd.read_excel("/content/home_price_multi_variable.xlsx")

In [24]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [33]:
import math 
bedroom_median=math.floor(df.bedrooms.median())

In [34]:
bedroom_median

4

In [36]:
df.bedrooms=(df.bedrooms.fillna(bedroom_median))

In [37]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [39]:
model=linear_model.LinearRegression()
model.fit(df[['area',"bedrooms","age"]],df.price)

LinearRegression()

In [40]:
model.predict([[3000,3,40]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([498408.25158031])

In [41]:
model.predict([[2000,4,5]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([522844.81651827])

In [75]:
df=pd.read_excel("/content/hcl_interview_data.xlsx")

In [76]:
df



experince  test_score(out of 10)  interview_score(out of 10)  salary($)
0       NaN                    8.0                           9      50000
1       NaN                    8.0                           6      45000
2      five                    6.0                           7      60000
3       two                   10.0                          10      65000
4     seven                    9.0                           6      70000
5     three                    7.0                          10      62000
6       ten                    NaN                           7      72000
7    eleven                    7.0                           8      80000

In [77]:
df.experince.fillna('zero')

0      zero
1      zero
2      five
3       two
4     seven
5     three
6       ten
7    eleven
Name: experince, dtype: object

In [78]:
df['experince']=df.experince.fillna('zero')

In [79]:
df

experince  test_score(out of 10)  interview_score(out of 10)  salary($)
0      zero                    8.0                           9      50000
1      zero                    8.0                           6      45000
2      five                    6.0                           7      60000
3       two                   10.0                          10      65000
4     seven                    9.0                           6      70000
5     three                    7.0                          10      62000
6       ten                    NaN                           7      72000
7    eleven                    7.0                           8      80000

In [ ]:
df['experince']=[w2n.word_to_num(i) for i in df['experince']]

In [80]:
pip install word2number

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [81]:
from word2number import w2n

In [56]:
print(w2n.word_to_num('five'))

5


In [82]:
df['experince']=[w2n.word_to_num(i) for i in df['experince']]

In [83]:
df

experince  test_score(out of 10)  interview_score(out of 10)  salary($)
0          0                    8.0                           9      50000
1          0                    8.0                           6      45000
2          5                    6.0                           7      60000
3          2                   10.0                          10      65000
4          7                    9.0                           6      70000
5          3                    7.0                          10      62000
6         10                    NaN                           7      72000
7         11                    7.0                           8      80000

In [85]:
test_score=df['test_score(out of 10)'].median()

In [88]:
df['test_score(out of 10)']=df['test_score(out of 10)'].fillna(test_score)

In [89]:
df

experince  test_score(out of 10)  interview_score(out of 10)  salary($)
0          0                    8.0                           9      50000
1          0                    8.0                           6      45000
2          5                    6.0                           7      60000
3          2                   10.0                          10      65000
4          7                    9.0                           6      70000
5          3                    7.0                          10      62000
6         10                    8.0                           7      72000
7         11                    7.0                           8      80000

In [91]:
model=linear_model.LinearRegression()
model.fit(df[['experince','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression()

In [92]:
model.predict([[2,9,6]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([53205.96797671])

In [93]:
model.predict([[12,10,10]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([92002.18340611])